### ISSUE TITLE
Feature to open diffs on new edits

### ISSUE THREAD

**Issue by invalidCards** [wikimedia/mediawiki-gadget-rtrc#101]
Just came across this project today, and it's really useful! I wonder how viable it would be to make a feature that automatically opens the diff of the latest edit as it comes in; that would make for some great AFK wiki patrolling.

**Comment by Krinkle** [comment]
I'm declining this for now, but feel free to create a new task at <https://phabricator.wikimedia.org/tag/gadget-rtrc/>.
