### ISSUE TITLE
Bug on *new update* of Vector 2022

### ISSUE THREAD

**Issue by hideonrosie** [wikimedia/mediawiki-gadget-rtrc#107]
![image](https://user-images.githubusercontent.com/88235604/215329549-a20e2e80-ef31-44b8-8e35-beda49ba2605.png)

With the new update of new Vector 2022, I got this bug when using RTRC (with limitation setting: 500 edits) on viwiki and enwiki. On other wiki without new update, RTRC worked normally.

**Comment by Krinkle** [comment]
It seems to work at the moment. If this is still an issue, please create a task at <https://phabricator.wikimedia.org/tag/gadget-rtrc/>. Thanks!
<img height="352" alt="Screenshot " src="https://github.com/wikimedia/mediawiki-gadget-rtrc/assets/156867/39663f6f-a20c-46d7-bf40-9137673efe50">
<img height="373" alt="Screenshot" src="https://github.com/wikimedia/mediawiki-gadget-rtrc/assets/156867/a2c7d354-8570-466c-a04a-83afc24e6465">
