### ISSUE TITLE
Localize the day number 

### ISSUE THREAD

**Issue by Huji** [wikimedia/mediawiki-gadget-rtrc#92]
In [line 200](https://gerrit.wikimedia.org/g/mediawiki/gadgets/RTRC/+/v1.4.0/src/rtrc.js#200) we have:

```
return '<div class="mw-rtrc-heading"><div><strong>' + date.getDate() + ' ' + monthNames[date.getMonth()] + '</strong></div></div>';
```

The issue is `date.getDate()` returns the day number in ASCII characters (e.g. 8) but some languages (e.g. Persian, Hindi, etc.) use other numerals.

`mw.language.convertNumber(date.getDate())` would fix it, assuming a dependency to `mw.language` is acceptable.

**Comment by Krinkle** [comment]
Sounds good to me! We could also adopt the `january-date`, `february-date`, etc messages while at it, so that we don't have to assume the preferred order of the number and the month name.

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T361301>.
